AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Basis Security Quick Starts - Single Account Deployment. Users have the ability to decide which resources to deploy. 

# Order the parameters in a way that makes more sense (not alphabetized)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Budget alerts configuration
      Parameters:
      - EnableBudgetAlerts
      - BudgetsSubscriptionEmail
      - BudgetName
      - BudgetCurrencyUnit
      - BudgetAmountLimit
      - BudgetFirstThreshold
      - BudgetSecondThreshold
      - BudgetTimeUnit
    - Label:
        default: GuardDuty configuration
      Parameters:
      - EnableGuardDuty
      - GuardDutyPublishingFrequency
    - Label:
        default: IAM Access Analyzer configuration
      Parameters:
      - EnableAnalyzer
      - AnalyzerName
      - AnalyzerType
    - Label:
        default: Security Hub configuration
      Parameters:
      - EnableSecurityHub
    - Label:
        default: WAF configuration
      Parameters:
      - CreateWAF
      - WAFType
      - WAFWebACLName
      - WAFWebACLMetricName

Conditions:
  AnalyzerEnabled:
    !Equals
    - !Ref EnableAnalyzer
    - 'true'
  BudgetAlertsEnabled:
    !Equals
    - !Ref EnableBudgetAlerts
    - 'true'
  CreateBudgetAlerts: !And 
    - !Condition BudgetAlertsEnabled
    - !Condition HasSubscriptionEmail
    - !Condition HasBudgetAmount
  CreateWAFClassic: !And
    - !Equals ["WAF_Classic", !Ref WAFType]
    - !Condition WAFCreationEnabled
  CreateWAFRegional: !And
    - !Equals ["WAF_Regional", !Ref WAFType]
    - !Condition WAFCreationEnabled
  CreateWAFV2: !And
    - !Equals ["WAF_V2", !Ref WAFType]
    - !Condition WAFCreationEnabled
  GuardDutyEnabled:
    !Equals
    - !Ref EnableGuardDuty
    - 'true'
  HasBudgetAmount: !Not 
    - !Equals 
      - !Ref BudgetAmountLimit
      - 0
  HasSubscriptionEmail: !Not 
    - !Equals 
      - !Ref BudgetsSubscriptionEmail
      - ''
  SecurityHubEnabled:
    !Equals
    - !Ref EnableSecurityHub
    - 'true'
  WAFCreationEnabled:
    !Equals
    - !Ref CreateWAF
    - 'true'

Parameters:
  AnalyzerName: 
    Default: "QuickStartAnalyser"
    Description: "The name of the IAM access analyzer."
    Type: String
  AnalyzerType:
    Default: "ACCOUNT"
    AllowedValues:
      - "ACCOUNT"
      - "ORGANIZATION"
    Description: "The type represents the zone of trust for the analyzer."
    Type: String
  BudgetAmountLimit:
    Type: Number
    Description: Enter budget amount limit for billing alarms.
    Default: 0
  BudgetCurrencyUnit:
    Type: String
    AllowedValues:
      - "AUD"
      - "BRL"
      - "CAD"
      - "CHF"
      - "CNY"
      - "DKK"
      - "EUR"
      - "GBP"
      - "HKD"
      - "JPY"
      - "KRW"
      - "NOK"
      - "NZD"
      - "SEK"
      - "SGD"
      - "USD"
      - "ZAR"
    Default: "USD"
    Description: Enter currency unit to use for budgets.
  BudgetName:
    Type: String
    Description: Name of the budget. 
    Default: "QuickStartBudgetNotification"
  BudgetFirstThreshold:
    Description: The first percentage threshold at which you'll receive a notification.
    Type: Number
    Default: 75
  BudgetSecondThreshold:
    Description: The second percentage threshold at which you'll receive a notification.
    Type: Number
    Default: 99
  BudgetTimeUnit:
    Type: String
    AllowedValues:
      - "ANNUALLY"
      - "QUARTERLY"
      - "MONTHLY"
      - "DAILY"
    Default: "MONTHLY"
    Description: Enter the length of time until a budget resets the actual and forecasted spend.
  BudgetsSubscriptionEmail:
    Type: String
    Description: Enter the email to subscribe to budgets notification.
    Default: ''
  CreateWAF:
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Create AWS Web Application Firewall to manage traffic rules."
    Type: String
  EnableAnalyzer: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Creates IAM access analyzer resource to identify unintended access to your resources and data."
    Type: String
  EnableBudgetAlerts: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Creates budget alert email notifications. If set to true, budget subscription email and budget amount must also be defined for alert to be created."
    Type: String
  EnableGuardDuty: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Creates GuardDuty detector resource to analyse AWS data sources to detect potential threats."
    Type: String
  EnableSecurityHub: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Enables SecurityHub which checks the current security state against industry standards and best practices across AWS accounts."
    Type: String
  GuardDutyPublishingFrequency:
    AllowedValues: 
      - "FIFTEEN_MINUTES"
      - "ONE_HOUR"
      - "SIX_HOURS"
    Default: "FIFTEEN_MINUTES"
    Description: "Specifies how frequently updated findings are exported."
    Type: String
  WAFWebACLMetricName:
    Default: "ExampleWebACLMetric"
    Description: "The name of the metrics for this WebACL. The name can contain only the characters A-Z, a-z, 0-9, - (hyphen), and _ (underscore). The name can be from one to 128 characters long. It can't contain whitespace or metric names reserved for AWS WAF, for example 'All' and 'Default_Action'. You cannot change the name of a web ACL after you create it."
    Type: String
  WAFWebACLName:
    Type: String
    Description: The name of the web ACL. You cannot change the name of a web ACL after you create it.
    Default: "QuickStartWebACL"
  WAFType:
    AllowedValues:
      - "WAF_Classic"
      - "WAF_Regional"
      - "WAF_V2"
    Default: "WAF_V2"
    Description: "Specifies type of AWS WAF to deploy."
    Type: String
Resources:
    ## Access and role analysis with IAM access analyzer
    Analyzer:
      Condition: AnalyzerEnabled
      Type: 'AWS::AccessAnalyzer::Analyzer'
      Properties:
        AnalyzerName: !Ref AnalyzerName
        Type: !Ref AnalyzerType
        Tags:
          - Key: Name
            Value: !Ref AWS::StackName
    ## Setup billing alarms 
    BudgetNotification:
      Condition: CreateBudgetAlerts
      Type: AWS::Budgets::Budget
      Properties: 
        Budget: 
          BudgetName: !Ref BudgetName
          # User input budget amount, currency unit and time unit 
          BudgetLimit:
            Amount: !Ref BudgetAmountLimit
            Unit: !Ref BudgetCurrencyUnit
          TimeUnit: !Ref BudgetTimeUnit 
          BudgetType: COST
        # User input subscription email for alerts
        # "A budget can have up to five notifications. Each notification must have at least one subscriber.
        # A notification can have one SNS subscriber and up to ten email subscribers, for a total of 11 subscribers."
        NotificationsWithSubscribers: 
          - Notification:
              NotificationType: ACTUAL
              ComparisonOperator: GREATER_THAN
              Threshold: !Ref BudgetFirstThreshold
              ThresholdType: PERCENTAGE
            Subscribers:
              - SubscriptionType: EMAIL
                Address: !Ref BudgetsSubscriptionEmail
          - Notification:
              NotificationType: ACTUAL
              ComparisonOperator: GREATER_THAN
              Threshold: !Ref BudgetSecondThreshold
              ThresholdType: PERCENTAGE
            Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref BudgetsSubscriptionEmail
          - Notification:
              ComparisonOperator: GREATER_THAN
              NotificationType: FORECASTED
              Threshold: 100
              ThresholdType: PERCENTAGE
            Subscribers:
              - SubscriptionType: EMAIL
                Address: !Ref BudgetsSubscriptionEmail
    ## Enables GuardDuty
    GuardDutyDetector:
      Condition: GuardDutyEnabled
      Type: AWS::GuardDuty::Detector
      Properties: 
        Enable: true
        # An enum value that specifies how frequently updated findings are exported.
        FindingPublishingFrequency: !Ref GuardDutyPublishingFrequency
    ## Implements Security Hub service, resource is created in region where CF stack is deployed
    SecurityHub:
      Condition: SecurityHubEnabled
      Type: AWS::SecurityHub::Hub
      Properties:
        Tags:
          Name: !Ref AWS::StackName
    ## Creates WAF Classic WebACL
    WAFClassicWebACL: 
      Condition: CreateWAFClassic
      Type: "AWS::WAF::WebACL"
      Properties: 
        Name: !Ref WAFWebACLName
        DefaultAction: 
          Type: "BLOCK"
        MetricName: !Ref WAFWebACLMetricName
    ## Creates WAF Regional WebACL
    WAFRegionalWebACL: 
      Condition: CreateWAFRegional
      Type: "AWS::WAFRegional::WebACL"
      Properties:
        Name: !Ref WAFWebACLName
        DefaultAction: 
          Type: "BLOCK"
        MetricName: !Ref WAFWebACLMetricName
    ## Creates WAF V2 WebACL
    WAFV2WebACL: 
      Condition: CreateWAFV2
      Type: "AWS::WAFv2::WebACL"
      Properties:
        Name: !Ref WAFWebACLName
        Scope: REGIONAL
        DefaultAction:
          Block: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: !Ref WAFWebACLMetricName

Outputs:
  AnalyzerARN:
    Condition: AnalyzerEnabled
    Description: "ARN of the analyzer created."
    Value: !Ref Analyzer
  BudgetName:
    Condition: CreateBudgetAlerts
    Description: "Name of the budget created for alert email notifications."
    Value: !Ref BudgetNotification
  GuardDutyDetectorID: 
    Condition: GuardDutyEnabled
    Description: "The unique ID of the GuardDuty detector resource."
    Value: !Ref GuardDutyDetector
  SecurityHubArn:
    Condition: SecurityHubEnabled
    Description: "HubARN of security hub resource created."
    Value: !Ref SecurityHub
  WAFClassicWebACLID:
    Condition: CreateWAFClassic
    Description: "The logical ID of the WAF Classic Web ACL resource."
    Value: !Ref WAFClassicWebACL
  WAFRegionalWebACLID:
    Condition: CreateWAFRegional
    Description: "The logical ID of the WAF Regional Web ACL resource."
    Value: !Ref WAFRegionalWebACL
  WAFV2WebACLDetails:
    Condition: CreateWAFV2
    Description: "The resource name, physical ID, and scope of the WAF Regional Web ACL resource."
    Value: !Ref WAFV2WebACL